### PR TITLE
Try to handle when a url is protocol-agnostic.

### PR DESCRIPTION
**Pull request by henrytndrly**
i.e. the URL is formatted to work for whatever the current protocol is - i.e. http:// or https://

e.g. https://www.bbc.co.uk/news has a protocol agnostic meta tag:
`<meta property="og:image" content="//m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/bbc_news_logo.png?cb=1">`

### CODE REVIEW

**Comment by adrienthiery** [comment]
Hi @henrytndrly,

Thanks a lot for the PR!

I sadly don't have the time to check that it works with all the urls this weekend but I'll check that out next week.

**Comment by adrienthiery** [comment]
Hey @henrytndrly,

I finally added the automated tests and ran them on your PR, and the result was the following :
```
  Parser
    ✓ should parse a URL with minified HTML correctly (1949ms)
    ✓ should parse a redirection correctly (1739ms)
    ✓ should parse an HTTP Only website correctly (1164ms)
    ✓ should parse a non latin character website correctly (734ms)
    ✓ should parse a website that allows only google bot through if programmatically called correctly (2306ms)
    ✓ should parse a URL with a relative image url correctly (736ms)
    ✓ should parse a URL with 's in the content correctly (634ms)
    1) should parse a URL with a protocol agnostic image in HTTPS correctly
    2) should parse a URL with a protocol agnostic image in HTTP correctly


  7 passing (12s)
  2 failing

  1) Parser should parse a URL with a protocol agnostic image in HTTPS correctly:

      AssertionError: expected '//m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/bbc_news_logo.png?cb=1' to equal 'https://m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/bbc_news_logo.png?cb=1'
      + expected - actual

      -//m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/bbc_news_logo.png?cb=1
      +https://m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/bbc_news_logo.png?cb=1

      at test/parser.js:111:39
      at process._tickCallback (internal/process/next_tick.js:103:7)

  2) Parser should parse a URL with a protocol agnostic image in HTTP correctly:

      AssertionError: expected '//m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/bbc_news_logo.png?cb=1' to equal 'http://m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/bbc_news_logo.png?cb=1'
      + expected - actual

      -//m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/bbc_news_logo.png?cb=1
      +http://m.files.bbci.co.uk/modules/bbc-morph-news-waf-page-meta/1.2.0/bbc_news_logo.png?cb=1

```

I think the URL returned by the parser should follow the protocol the page has been requested with, don't you think ? Or should it stay protocol agnostic?

Do you think you could rebase your branch on `master` so Travis runs the tests directly ?

**Comment by henrytndrly** [comment]
I suppose that's something that would be good to happen - use whatever protocol was requested to 'populate' the image's protocol... That way code doesn't have to try to handle it later... (if you're not using it in a browser!)

I'll see what I can come up with...

**Comment by henrytndrly** [comment]
Hi @adrienthiery,

I've updated my changes so that it should handle http and https protocol agnostic URLs. I've only handled them, as I'm not sure of what 'unintended consequences' could happen when handling generic/custom protocols...

**Comment by adrienthiery** [comment]
@henrytndrly : Nice ! :+1:

**Pull request merged**
